export const SUCCESS_LOAD_NOTES = 'SUCCESS_LOAD_NOTES';
export const SUCCESS_SAVE_NOTES = 'SUCCESS_SAVE_NOTES';
export const SUCCESS_LOAD_NEWS = 'SUCCESS_LOAD_NEWS';

export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";
